
import { useState } from "react";
import Ripples from 'react-ripples';

import Dialog from '@material-ui/core/Dialog';
import DialogContent from '@material-ui/core/DialogContent';
import DialogTitle from '@material-ui/core/DialogTitle';
// import TouchRipple from '@material-ui/core/TouchRipple';

import FontIcon from "../../FontIcon/FontIcon";

import '../ChartSummaryModal/ChartSummaryModal.scss';

const ArtistAnalysisModal = () => {

    const [anchorEl, setAnchorEl] = useState(null);
    const [openel, setOpenel] = useState(false);

    const open = Boolean(anchorEl);


    const handleClick = (event) => {
        setAnchorEl(event.currentTarget);
        setOpenel(true);
    };

    const handleCloseEl = () => {
        setOpenel(false);
    };

    return (
        <div className="artistanalysis-modal-component">
            <div className="date-content" onClick={handleClick} open={open} role="presentation" >
                <Ripples >
                    <FontIcon iconName="info_circle" size="medium" color="grey" tooltip="Info" onClick={handleClick} open={open} role="presentation" />
                </Ripples>
            </div>
            <Dialog open={openel} onClose={handleCloseEl} className="model-template artistanalysis-modal">
                <DialogTitle>
                    <div className="modal-title">
                        <FontIcon iconName="info_circle" size="medium" />
                        <div className="chart-title">
                            <div>Artist Analysis</div>
                            <div className="modal-subtext">Deep-dive into artist level chart performance.</div>
                        </div>
                    </div>
                    <div className="cross-icon">
                        <Ripples >
                            <FontIcon
                                iconName="cross"
                                size="small"
                                onClick={handleCloseEl}
                            />
                        </Ripples>
                    </div>
                </DialogTitle>
                <DialogContent>
                    <div className="chart-modal-content">
                        <div className="chart-points Artist-based ">
                            <div className="modal-title">Analyse artist’s performance trends through 4 lenses:</div>
                            <ol className="modal-subtext">
                                <li>Chart total (Overall top 200 performance)</li>
                                <li>Labels</li>
                                <li>Local vs. International</li>
                                <li>Rank categories (track positions categorised in buckets such as 1 to 5, 6 to 10 etc.)</li>
                            </ol>
                        </div>
                        <div className="chart-points category-lenses ">
                            <div className="modal-title">Information can be viewed through 3 artist category lenses: </div>
                            <ol className="modal-subtext">
                                <li>Charting artists – Unique primary artists appearing on the chart (if an artist has 2 or more songs on the chart, with different collaborators, it will be still counted as one artist)</li>
                                <li>Debut artists – Artists who have never released a song before on Spotify </li>
                                <li>Breakthrough artists - Artists who feature on the Top 200 after 9 months or more</li>
                            </ol>
                        </div>
                        <div className="chart-points analyse-options">
                            <div className="modal-title">Analyse using 3 view options:</div>
                            <ol className="modal-subtext">
                                <li>No. of artists – Unique primary artists appearing on the chart (if an artist has 2 or more songs on the chart, with different collaborators, it will be still counted as one artist)</li>
                                <li>Total streams – Volume of chart streams generated by selected artist category</li>
                                <li>Avg. stream per track – Weekly average of chart streams generated by selected artist category</li>
                            </ol>
                        </div>
                        <div className="chart-points analyse-options">
                            <div className="modal-title">Identify artist trends:</div>
                        </div>
                        <div className="modal-subtext">Select a data point on the trend line to show the artist list based on your selection in the table below</div>
                        <div className="modal-subtext">Click on the artist’s name for more information about their chart performance</div>
                    </div>
                </DialogContent>
            </Dialog>

        </div>
    );
}

export default ArtistAnalysisModal;